name: CI

on:
  pull_request:
  push:
    branches:
      - trunk
    tags-ignore:
      - '**'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SCALA_VERSION_DOC: 2.13.12

jobs:
  run:
    name: Build and Test and Publish pages
    strategy:
      matrix:
        java-version: [21]
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - uses: coursier/cache-action@v6

      - name: Run all tests (but the slow ones)
        run: ./mill main.__.test.testCached

      - name: Generate html docs
        run: ./mill main.__.docJar

      - name: Generate html scoverage report
        run: | 
          ./mill main.__.scoverage.htmlReport
          mv ./out/main/${{ env.SCALA_VERSION_DOC }}/scoverage/htmlReport.dest \
             ./out/main/${{ env.SCALA_VERSION_DOC }}/docJar.dest/javadoc/scoverage

      - name: Setup pages
        if: github.ref == 'refs/heads/trunk'
        uses: actions/configure-pages@v3

      - name: Upload artifact
        if: github.ref == 'refs/heads/trunk'
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./out/main/${{ env.SCALA_VERSION_DOC }}/docJar.dest/javadoc"

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/trunk'
        uses: actions/deploy-pages@v2
